apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowcollector-deployment
  namespace: wowcollector
spec:
  selector:
    matchLabels:
      app: wowcollector-app
  template:
    metadata:
      labels:
        app: wowcollector-app
        app/hash: {{hash}}
    spec:
      containers:
        - name: wowcollector-app
          image: tovven/wowcollector:{{tag}}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/v1/monitoring/readiness
              port: 8000
            initialDelaySeconds: 10
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: connection
            - name: BATTLE_NET_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: blizzard-creds
                  key: clientId
            - name: BATTLE_NET_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blizzard-creds
                  key: secret
            - name: APPLICATION_URL
              value: "https://wowcollector.io"
            - name: QUARKUS_HTTP_PORT
              value: "8000"
            - name: WOW_MONGODB_DATABASE
              value: wow
            - name: QUARKUS_CACHE_CAFFEINE_EXPIRE_AFTER_WRITE
              value: "600"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-creds
                  key: secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wowcollector-ingress
  namespace: wowcollector
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - wowcollector.io
      secretName: k8s-consolejs-net
  rules:
    - host: "wowcollector.io"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: wowcollector-svc
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wowcollector-svc
  namespace: wowcollector
spec:
  selector:
    app: wowcollector-app
  ports:
    - name: wowcollector-app
      protocol: TCP
      port: 80
      targetPort: 80