export interface TooltipInfo {
  name: string | null;
  itemLevel: number | null;
  bindType: string | null;
  mountType: string | null;
  raceRequirement: string | null;
  use: string | null;
  summon: string | null;
  minLevel: number | null;
  maxLevel: number | null;
  currentLevel: number | null;
  requirement: string | null;
  sellPrice: number | null;
  lore: string | null;
  drop: string | null;
  vendor: string | null;
  location: string | null;
  cost: number | null;
  dropChance: number | null;
  quest: string | null;
  zone: string | null;
  achievement: string | null;
  category: string | null;
}
