export enum Icons {
  // mdi
  HOME = 'mdi-view-dashboard',
  MOUNTS = 'mdi-horse-variant',
  ACHIEVEMENTS = 'mdi-trophy',
  ACCOUNT = 'mdi-account',
  ACCOUNT_GROUP = 'mdi-account-group',
  LOGOUT = 'mdi-logout',
  SEARCH = 'mdi-magnify',
  REMOVE_SEARCH = 'mdi-magnify-remove-outline',
  ACCOUNT_CIRCLE = 'mdi-account-circle',
  QUESTION_MARK = 'mdi-help',
  MALE = 'mdi-gender-male',
  FEMALE = 'mdi-gender-female',
  WARN = 'mdi-alert-outline',
  CHEVRON_DOWN = 'mdi-menu-down',
  CHEVRON_UP = 'mdi-menu-up',
  COLLECTABLES = 'mdi-treasure-chest',
  STAR = 'mdi-star',
  STAR_OUTLINE = 'mdi-star-outline',
  GRID_COMPACT = 'mdi-view-grid-compact',
  GRID = 'mdi-view-grid',
  LIST = 'mdi-view-list',
  SETTINGS = 'mdi-cog',
  PREFERENCES = 'mdi-tune',
  TOOLTIP_TEXT = 'mdi-tooltip-text',
  TOOLTIP_IMAGE = 'mdi-tooltip-image',

  // Custom
  LOGO = 'custom:logo',
  BATTLENET = 'custom:battlenet',
  TANK = 'custom:tank',
  HEALER = 'custom:healer',
  DPS = 'custom:dps',
  DEATH_KNIGHT = 'custom:deathKnight',
  DEMON_HUNTER = 'custom:demonHunter',
  DRUID = 'custom:druid',
  EVOKER = 'custom:evoker',
  HUNTER = 'custom:hunter',
  MAGE = 'custom:mage',
  MONK = 'custom:monk',
  PALADIN = 'custom:paladin',
  PRIEST = 'custom:priest',
  ROGUE = 'custom:rogue',
  SHAMAN = 'custom:shaman',
  WARLOCK = 'custom:warlock',
  WARRIOR = 'custom:warrior',
}
