export const SpecializationsMap: Record<string, string> = {
  Affliction: 'DPS',
  Arcane: 'DPS',
  Arms: 'DPS',
  Assassination: 'DPS',
  Balance: 'DPS',
  'Beast Mastery': 'DPS',
  Blood: 'TANK',
  Brewmaster: 'TANK',
  Demonology: 'DPS',
  Destruction: 'DPS',
  Discipline: 'HEALER',
  Elemental: 'DPS',
  Enhancement: 'DPS',
  Feral: 'DPS',
  Fire: 'DPS',
  Frost: 'DPS',
  Fury: 'DPS',
  Guardian: 'TANK',
  Havoc: 'DPS',
  Holy: 'HEALER',
  Marksmanship: 'DPS',
  Mistweaver: 'HEALER',
  Outlaw: 'DPS',
  Protection: 'TANK',
  Restoration: 'HEALER',
  Retribution: 'DPS',
  Shadow: 'DPS',
  Subtlety: 'DPS',
  Survival: 'DPS',
  Unholy: 'DPS',
  Vengeance: 'TANK',
  Windwalker: 'DPS',
};
